### ISSUE TITLE
Leaving room with AI causes zombie room

### ISSUE THREAD

**Issue by AlphaKretin** [edo9300/ygopro#106]
Platform: MacOSX Catalina
Version: Last updated roughly 9:30 AM 15/02 ACDT
Steps to reproduce:
 - Host a room in LAN Mode
 - Call the Local AI
 - Exit the LAN room
 - Attempt to host a new room, observe that you cannot
 - Refresh the LAN room list, observe that the last room hosted is still there
 - Join the room, observe that your player name and the AI are still listed as players, and you are a spectator.

**Comment by kevinlul** [comment]
Notes: WindBot stays alive. Host player is not shown as leaving the room. Does not occur if WindBot is spawned independently instead of from fork-exec. Needs verification on Linux.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/692df3d0ade42cdd59618efff28b4d1a1cbf3f9a

**Comment by AlphaKretin** [comment]
I can still replicate the issue after updating just now.

**Comment by edo9300** [comment]
Tested and fully fixed in https://github.com/edo9300/ygopro/commit/990767541ddaff26298986182abc45384d520ef5
