### ISSUE TITLE
Going second, decks are offset in a Tag Duel

### ISSUE THREAD

**Issue by AlphaKretin** [edo9300/ygopro#116]
Discovered in a 3vs3 Tag Duel, unfortunately, the replay could not be saved. The team that went second had their decks offset by 1 compared to the players, so people were playing with the wrong deck. The example, to help explain:

pyrQ selected Cubics, AlphaKretin selected Eldlich, JustGian selected Tindangle. In Percy (ignoring that it can't do 3v3 tags), the active player for the team during Turn 1 would be Gian with Tindangles, then at the start of Turn 2, it would change to pyrQ with Cubics. In this situation, I failed to note the player name on Turn 1 (we think it was pyrQ), but it started with Cubics, then changed to pyrQ with Eldlich.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/c8833597f03e2b46daf77b0d4c95798924703973
