### ISSUE TITLE
Stale game data preserved between games while spectating

### ISSUE THREAD

**Issue by AlphaKretin** [edo9300/ygopro#118]
While spectating a game between other players, when they go into a second game e.g. through a rematch the board state from the previous game is preserved and the game state for the new game is stacked on top of it.
![image](https://puu.sh/Fdcqy/412907adfb.png)
Some details can be overridden (the Madolche monster had an inherent summon in its location override it), but when a Nibiru attempted to Tribute the whole field, which at the time included the stale Nibiru Token, the client crashed for all spectators (on both Mac and Windows). [Mac crash dump](https://cdn.discordapp.com/attachments/281062530955345920/680621560792612866/stale_spectator_crash.txt).

**Comment by AlphaKretin** [comment]
Upon reloading the game, the room is still visible (they might legitimately be still trying to play?) and as the client attempts to catch up to the game state it reaches the point at which it crashed before. It then says the game ends, but the client crashes after cancelling the replay prompts.
![image](https://puu.sh/Fdd31/f073657138.png)

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/1bcc5eacbe1ccfcaf9c719f7d12ba91a6e5081c7
