### ISSUE TITLE
Skill cards not displayed during online Duel

### ISSUE THREAD

**Issue by AlphaKretin** [edo9300/ygopro#119]
During a Duel involving Skill Cards on a server, they are not drawn on the field.
![image](https://cdn.discordapp.com/attachments/586821870070792223/680625278384472092/unknown.png)

However, during a replay, they are, but only if started from the first turn.
![image](https://cdn.discordapp.com/attachments/586821870070792223/680625278384472092/unknown.png)
![image](https://puu.sh/Fddbh/2fafacb750.png)

**Comment by edo9300** [comment]
Skills not shown during replay fixed in c3ffc23e4711b0e957906a143fef06e8543c3a9e

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/0218d5807bd4a0e7b864ad53f4cacc00d08ff9d2
