### ISSUE TITLE
Wiki: Document where to get up-to-date scripts

### ISSUE THREAD

**Issue by LordYuuma** [edo9300/ygopro#125]
While the source code appears to allow downloading card databases and scripts from external sources, the only sources referenced in any of the Travis scripts have last been updated way back in 2019.  The Fluorohydride/mycard databases work fine as far as deck building is concerned, but their scripts appear to break, specifically when the extra deck is involved.

**Comment by kevinlul** [comment]
This project is not related to card scripts.

**Comment by LordYuuma** [comment]
Not to be rude or anything, but I am fairly certain the game loads scripts as part of its expected runtime behaviour.  What other purpose does `Game::ScriptReader` serve if not?
