### ISSUE TITLE
Problems of missing file during build with visual 2019

### ISSUE THREAD

**Issue by ArnaudSushi** [edo9300/ygopro#131]
Hello,

I'm trying too install edopro and during the building step I get a lot of missing file error (most of them about lua.h), see attached file for a screen capture.

Thanks in advance.
![errer](https://user-images.githubusercontent.com/24224993/78505173-fabe3280-7771-11ea-974d-19a0affe7d75.PNG)
![errer2](https://user-images.githubusercontent.com/24224993/78505174-fb56c900-7771-11ea-8660-d5146d7efa5b.PNG)

**Comment by kevinlul** [comment]
Please follow the build instructions on [the wiki](https://github.com/edo9300/ygopro/wiki). You did not install any of the dependencies.

**Comment by ArnaudSushi** [comment]
Thanks for pointing to it, the dependencies weren't installed because I didn't have the English language package for visual studio, I'm installing the dependencies now

**Comment by ArnaudSushi** [comment]
So, I installed everything again, the build passed, but the command
`./travis/quickrun.sh debug|release`
doesn't seem to work, i get the error
![err](https://user-images.githubusercontent.com/24224993/78506538-70c69780-777a-11ea-975f-c5db92c15e14.PNG)
