### ISSUE TITLE
Update fonts

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#17]
SimHei and Arial are copyrighted, no place to download. Look at Google Open Fonts for ideas? Open Sans? ~~Segoe?~~

Decide whether `system.conf` points to generic names or actual font names.

**Comment by AndreOliveiraMendes** [comment]
try to find a good stardant one that is open and free and put the actual font name, then later in case someone wanna customize maybe aditing instruction of how to do should be fine.

**Comment by kevinlul** [comment]
[Google Open Fonts](https://github.com/google/fonts)

Popular fonts:
- [Roboto](https://fonts.google.com/specimen/Roboto)
- [Open Sans](https://fonts.google.com/specimen/Open+Sans)
- [Noto](https://fonts.google.com/?query=Noto) supports East Asian glyphs as well

**Comment by DyXel** [comment]
In game screenshot are welcome, so we can compare side to side which one looks better

**Comment by kevinlul** [comment]
Some examples.

Noto Sans, Regular | Open Sans, Regular | Open Sans, Light | Roboto, Regular | Roboto, Black
--- | --- | --- | --- | ---
<img width="372" alt="SplashNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786296-f3867080-9294-11e9-9e39-ce49f65cb730.png"> | <img width="411" alt="SplashOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786307-f4b79d80-9294-11e9-82d7-ec7f23b4f582.png"> | <img width="409" alt="SplashOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786300-f41f0700-9294-11e9-9d44-9d6f65316f53.png"> | <img width="410" alt="SplashRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786297-f3867080-9294-11e9-85fb-0e55859197dc.png"> | <img width="410" alt="SplashRobotoBlack" src="https://user-images.githubusercontent.com/6320810/59786312-f4b79d80-9294-11e9-8c87-69df93c7a632.png">
<img width="369" alt="DeckNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786295-f3867080-9294-11e9-883a-3132e44a57fc.png"> | <img width="410" alt="DeckOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786308-f4b79d80-9294-11e9-9210-568a3fd6a2dc.png"> | <img width="410" alt="DeckOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786299-f41f0700-9294-11e9-975b-b3d849d484ca.png"> | <img width="409" alt="DeckRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786298-f3867080-9294-11e9-921e-1c59412016e3.png"> | <img width="410" alt="DeckRobotoBlack" src="https://user-images.githubusercontent.com/6320810/59786310-f4b79d80-9294-11e9-8cac-967e6a9d8bf7.png">
<img width="371" alt="ReplayNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786306-f4b79d80-9294-11e9-8cb4-0022237e370e.png"> | <img width="410" alt="ReplayOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786311-f4b79d80-9294-11e9-9c3c-7be7c4c7cc9b.png"> | <img width="408" alt="ReplayOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786301-f41f0700-9294-11e9-9f35-23d6854cbb3b.png"> | <img width="409" alt="ReplayRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786302-f41f0700-9294-11e9-98f0-efc514ae3180.png"> |
<img width="371" alt="LANNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786305-f41f0700-9294-11e9-9d87-284d1cbb92eb.png"> | <img width="411" alt="LANOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786309-f4b79d80-9294-11e9-9b0d-34a257131b98.png"> | <img width="409" alt="LANOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786303-f41f0700-9294-11e9-8ff0-4a30d95f25fa.png"> | <img width="408" alt="LANRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786304-f41f0700-9294-11e9-847d-4e11fe374507.png"> |

List form:
<img width="372" alt="SplashNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786296-f3867080-9294-11e9-9e39-ce49f65cb730.png"><img width="411" alt="SplashOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786307-f4b79d80-9294-11e9-82d7-ec7f23b4f582.png"><img width="409" alt="SplashOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786300-f41f0700-9294-11e9-9d44-9d6f65316f53.png"><img width="410" alt="SplashRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786297-f3867080-9294-11e9-85fb-0e55859197dc.png"><img width="410" alt="SplashRobotoBlack" src="https://user-images.githubusercontent.com/6320810/59786312-f4b79d80-9294-11e9-8c87-69df93c7a632.png">
<img width="369" alt="DeckNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786295-f3867080-9294-11e9-883a-3132e44a57fc.png"><img width="410" alt="DeckOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786308-f4b79d80-9294-11e9-9210-568a3fd6a2dc.png"><img width="410" alt="DeckOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786299-f41f0700-9294-11e9-975b-b3d849d484ca.png"><img width="409" alt="DeckRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786298-f3867080-9294-11e9-921e-1c59412016e3.png"><img width="410" alt="DeckRobotoBlack" src="https://user-images.githubusercontent.com/6320810/59786310-f4b79d80-9294-11e9-8cac-967e6a9d8bf7.png">
<img width="371" alt="ReplayNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786306-f4b79d80-9294-11e9-8cb4-0022237e370e.png"><img width="410" alt="ReplayOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786311-f4b79d80-9294-11e9-9c3c-7be7c4c7cc9b.png"><img width="408" alt="ReplayOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786301-f41f0700-9294-11e9-9f35-23d6854cbb3b.png"><img width="409" alt="ReplayRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786302-f41f0700-9294-11e9-98f0-efc514ae3180.png"> 
<img width="371" alt="LANNotoSansRegular" src="https://user-images.githubusercontent.com/6320810/59786305-f41f0700-9294-11e9-9d87-284d1cbb92eb.png"><img width="411" alt="LANOpenSansRegular" src="https://user-images.githubusercontent.com/6320810/59786309-f4b79d80-9294-11e9-9b0d-34a257131b98.png"><img width="409" alt="LANOpenSansLight" src="https://user-images.githubusercontent.com/6320810/59786303-f41f0700-9294-11e9-8ff0-4a30d95f25fa.png"><img width="408" alt="LANRobotoRegular" src="https://user-images.githubusercontent.com/6320810/59786304-f41f0700-9294-11e9-847d-4e11fe374507.png">

**Comment by DyXel** [comment]
I like the Roboto Regular one. Looks decent, nothing too fancy, gets the job done.

**Comment by LogicalNonsense2051** [comment]
- Open Sans, Regular 
- Noto Sans, Regular
- Roboto, Regular
Of the five given fonts, those three seem fine to me.

**Comment by AndreOliveiraMendes** [comment]
i like the Open Sans, Regular one, it looks decent to me.
im fine with roboto, too trought.

**Comment by pyrQ** [comment]
I'm between Noto Sans Regular and Open Sans Regular, but I think I prefer the Opens Sans one.

**Comment by NaimSantos** [comment]
I prefer Open Sans Regular, among the ones listed.

**Comment by NaimSantos** [comment]
I'd like to mention that Open Sans and Robot Regular [the ones i tested] and probably the others, don't have support for characters like the dot used in cards like **Saryuja Skull Dread**: ●, so card text with those will miss those.

**Comment by kevinlul** [comment]
I think we have to use a Noto variant to support card text in East Asian languages. The dot isn't used in any English/Latin alphabet card names, right?

**Comment by AlphaKretin** [comment]
There are cards that use some variety of interpunct, at least: "Summon Reactor・SK" and it's other two terrible friends. We also need to be wary of "Mariña, Princess of Sunflowers" and "Chirubimé, Princess of Autumn Leaves", among other characters with diacritics that don't display with some fonts (notably the current default on Percy).

**Comment by kevinlul** [comment]
Noto Sans SC/TC/HK/JP supports all of those. Test string: ["Mariña Chirubimé ・SK"](https://fonts.google.com/?query=Noto)

**Comment by AlphaKretin** [comment]
Oh, I feel bad for not mentioning this before, but I forgot until now: There's "Fiendish Engine Ω" and "Kuwagata α" too. A lot of these Noto variants seem to support either "・" or Greek letters, but not both.

**Comment by AlphaKretin** [comment]
OK, I've found [https://yugipedia.com/wiki/User:SnorlaxMonster/Sandbox#TCG_cards_with_non-ASCII_English_names](a list) of all such cards maintained by a Yugipedia editor. I'll edit this page with a test string after compiling it, and then the results.

**Comment by AlphaKretin** [comment]
I figured out the issue I was having with JP and HK. When I clicked on a sample to edit it, it changed to a different font that didn't display them. If I enter the test string in the bar at the top, all 4 mentioned fonts seem fine.

However, when presenting the list above, I forgot about anime cards.* Besides "Meklord Emperor Granel ∞" and "Conduction Warrior Linear Magnum ±", which display correctly, there's also "Magnet Warrior Σ＋". Σ does *not* appear to display correctly in any of the Noto fonts.
Test string: "Chirubimé Cú Ür Mariña    ☆ ・SK ∞Σ±"
Results: 
![jp kr](https://puu.sh/DIib1/0c154e4702.png)
![tc sc](https://puu.sh/DIibj/ca166a73b9.png)

*If you're thinking about whether we should care about anime cards or not, I think that's besides the point. Some symbols like ∞ do appear in official Japanese card names, and in any case they just serve of examples of other characters that could hypothetically appear in card names. It's good to future-proof a decision like this.

**Comment by kevinlul** [comment]
I'm kind of also thinking of fonts from an i18n perspective, though there's no reason we couldn't swap between fonts for language; in fact, I think a lot of apps do that.

**Comment by AlphaKretin** [comment]
The issue of the specific fonts is kind of academic at this point, but I found a more comprehensive [list](https://yugipedia.com/wiki/User:Dinoguy1000/weird_card_names#%C2%B1_(plus-minus_sign)) elsewhere on Yugipedia, for the curious.

**Comment by AndreOliveiraMendes** [comment]
acording dyxel, we should use combination of multiple fonts (so rewrite it so it can load multiple fonts) as one font generaly can't have that many symbols and software in general uses multiple fonts to cover the eventual gaps in one font. dyxel -2019

**Comment by DyXel** [comment]
Yeah, thats the gist of it. We should choose one font family and grab all its flavors. The font drawing system is the responsible for choosing the right glyphs according to all the font files it has available. Like andre quoted, eventually, no matter which font we choose; we will have a gap, because those fonts families are meant to be used together, not grab a single file that has "most" of the glyphs and leave everything else out. Now, i have no idea how to deal with this on irrlicht OR with freetype. It will be up to someone to do the task, OR we can choose the "Regular" flavor of a font family, and inject the glyphs we need to it, and distribute that. Im not even sure if this is a valid approach from a legal standpoint..

**Comment by NaimSantos** [comment]
Test string should be updated to : "Chirubimé Cú Ür Mariña ☆ ・SK ∞Σ± ● Ω"

**Comment by NaimSantos** [comment]
I have changed the font provided in the current build to Noto Sans, as it is the one that seems to include all the characters. According to Google license is public domain, GPL, OFL.

**Comment by kevinlul** [comment]
Forgot about the wide characters. They should likely be rendered differently anyway, but reopening so we don't forget.

**Comment by kevinlul** [comment]
Noto Sans JP, TC, SC support these wide characters like Ｍ
