### ISSUE TITLE
Duel.SortDecktop crashes the client

### ISSUE THREAD

**Issue by NaimSantos** [edo9300/ygopro#25]
[In this puzzle](https://discordapp.com/channels/280403281308680192/281062530955345920/598616025260621824), the interaction can be tested with either Spellbook Organization or Dark Magical Circle. With Circle, the effect is executed up to the point where the Duel.SortDecktop function is called.

**Comment by edo9300** [comment]
Fixed https://github.com/edo9300/ygopro/commit/f688dc870393637382387eb0442af60298732a80
