### ISSUE TITLE
[macOS] Add "New Window" option in system menu

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#28]
Hopefully this is something simple in Cocoa.

**Comment by AlphaKretin** [comment]
To specify, the reason this is a feature desirable for MacOS specifically is that most intuitive methods of attempting to open a second window, such as double-clicking the executable a second time, do not work and only refocus on the existing instance, unlike in Windows. (I do not know how Linux works in this regard.)

**Comment by DyXel** [comment]
> (I do not know how Linux works in this regard.)
All known File Managers open a new instance of the application on default configurations when clicking the executable.
