### ISSUE TITLE
Monster stat display during battle

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#67]
Monster stats are not displayed correctly around battles if they are changed. Related to query handling in these steps. 

See puzzle 45
Make Star Eater DARK via DNA Transplant and have it gain 500 ATK via Mystic Plasma Zone.
Check with Mystik Wok that its stats have changed.
Have Star Eater attack. Note that the displayed stats do not reset to the original stats until the Damage Step.
Have Star Eater attack. Activate Mystik Wok during the Battle Step to verify that its stats indeed are the original.

**Comment by edo9300** [comment]
Should be fixed in 2232d825f89ca43f214470fbe33f5c9ba428a89a
