### ISSUE TITLE
Need an XML tag for hover tooltip background

### ISSUE THREAD

**Issue by griimnak** [edo9300/ygopro#79]
This is an old issue that has been expressed a few times on the forums
https://www.ygopro.co/Forum/tabid/95/g/posts/t/8864/Hover-Text-hard-to-read#post53556
https://www.ygopro.co/Forum/tabid/95/g/posts/t/24804/Question-about-skins#post124325

A simple solution would be an XML tag for the hover tooltip background.

Changing <EGDC_BUTTON_TEXT a="255" r="30" g="30" b="30" /> is not a good solution because it changes the text color globally

**Comment by edo9300** [comment]
Extra skin values have been added here https://github.com/edo9300/ygopro/commit/3b725e9bdb52262a82401ac4792e519f20d85bfb#diff-5959b7c103284051dea8f7dbb7b8a7d0R1935 .
to use them you have to put those values under the "Custom" node


	
```xml
<Skin>
	<Custom>
		<CARDINFO_TYPES_COLOR a="255" r="0" g="0" b="255" />
		<CARDINFO_STATS_COLOR a="255" r="0" g="0" b="255" />
		<CARDINFO_ARCHETYPE_TEXT_COLOR a="255" r="0" g="0" b="255" />
		<ROOMLIST_TEXTS_COLOR a="255" r="255" g="255" b="255" />
		<DUELFIELD_HOVERED a="255" r="255" g="255" b="255" />
	</Custom>
</Skin>
```
