### ISSUE TITLE
Watch Replay: Export Decks will silently fail if a player name is an invalid file name

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#82]
I've already added a solution to the [Netdecker](https://github.com/edo9300/netdecker/commit/d39d501b1f8cbbd3ca5fe209e2bac633ec47735d) to fall back to not including the player name if this happens.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/0a9e3fd44bf337212ae7c8c854687b598b8722ec
