### ISSUE TITLE
LAN Mode: Only the host player can save a replay

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#83]
This only happens for the last duel in a match (even BO1).

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/decb7deaddee13ae651bb9ee02902da619bd0250

**Comment by kevinlul** [comment]
Now no player can save a replay on the final duel of a match.

**Comment by edo9300** [comment]
Fixed in 3da289a90448627bccb3e73bba42e957966362f7
