### ISSUE TITLE
LAN Mode: Nobody may surrender if there are more than two players

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#84]
To reproduce: start any duel that is not a 1v1 and try to surrender. This also occurs for relays.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/56e443687b93f75924b113604de57606971db590

**Comment by kevinlul** [comment]
This works now; however, if the host surrenders sometime on reaching Main Phase 1, that client will crash. This is inconsistent so there might be a timing issue.

**Comment by kevinlul** [comment]
Not reproducible
