### ISSUE TITLE
LAN Mode: Players 3+ in relays get stuck in the side deck

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#85]
Only players 1 and 2 can get out of siding.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/70097b195784ffbba3762656bd8f38e22dca4694

**Comment by kevinlul** [comment]
Now if players 1 and 2 finish siding first, player 3 remains stuck but the duel will not proceed.

If player 2 and 3 are on the same team and player 3 finishing siding first, then player 2 cannot finish siding and gets a deck error if player 1 has not finished yet. If player 1 has finished then player 2 is stuck and the duel cannot start.

**Comment by kevinlul** [comment]
If two players on the same team finish siding first then the player on the other team is stuck in sidedeck and nobody gets prompted to start the duel.

**Comment by edo9300** [comment]
Should be fixed in ae48a993a4d0243523e1347fefb63fa0eb86816e
