### ISSUE TITLE
Top bar becomes uninteractive in a rare edge case

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#88]
If you don't interact with the top bar and proceed directly to Online Mode, it becomes noninteractable while in Online Mode. Clicking on it first somewhere else fixes the issue for the rest of the session.

**Comment by edo9300** [comment]
Fixed in https://github.com/edo9300/ygopro/commit/48cde99519ab7244a65e7ac81f8190aa12b5ed12
