### ISSUE TITLE
Mirror the fill of the LP bar for the opposing player

### ISSUE THREAD

**Issue by kevinlul** [edo9300/ygopro#93]
Should improve symmetry and aesthetics if a "gradient" style is used.

**Comment by AlphaKretin** [comment]
if we're aiming for symmetry, the direction the LP bar depletes should also be mirrored, like in a fighting game. Otherwise the mirrored gradients will look really strange. (If you meant that as part of this already, my bad).

**Comment by kevinlul** [comment]
They already deplete "mirrrored". I forget if the gradients being mirrored was solved today or not.

**Comment by edo9300** [comment]
The lp bar colors now can be midified indipendently per player
