### ISSUE TITLE
Speed Duel Skill activation error

### ISSUE THREAD

**Issue by AlphaKretin** [edo9300/ygopro#96]
In a Speed Duel, the activation circle for a Skill Card does not line up with the drawn location of the Skill Card, and neither location can be clicked to activate it. I could not find anywhere at all to click, in fact. 
![image](https://puu.sh/F4W65/72c3d7dd3f.png)

**Comment by edo9300** [comment]
Fixed in d1c165e3c4758ff4dc231b29d319a4043adc02a4
